### ISSUE TITLE
Can't connect to Wi-Fi: Space in the SSID

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#10]
![Screenshot from 2019-07-11 14-39-34](https://user-images.githubusercontent.com/484033/61048287-203c2c80-a3ea-11e9-98a1-648324d2ff7b.png)

My laptop is connected to a WiFi `@iLabAfrica - Boardroom`. However on the gateway UI I cannot find it. Only `@iLabAfrica` appears. My WiFi is WPA2 but this wifi on the gateway doesn't show security.

**Comment by cdupont** [comment]
Maybe it doesn't support spaces in the USSD?

**Comment by mojtaba-esk** [comment]
it is not designed to be run on a laptop as I said you will have issues with wifi. If you wanna fix it, you need to modify the api.py file in the system container and set your wifi interface there. I am planning to make that one as a env variable. However, it is designed to work on a RPI which uses wlan0 as iface name.

**Comment by mojtaba-esk** [comment]
> Maybe it doesn't support spaces in the USSD?

That might be the issue if you don't see it on raspberry pi.

**Comment by cdupont** [comment]
Yes this test was done on Raspberry PI.

**Comment by cdupont** [comment]
It seems that parsing the shell commands is difficult when there are spaces. So at the moment SSID with spaces is not accepted. A workaround it to use hidden networks field.

**Comment by mojtaba-esk** [comment]
Resolved
