### ISSUE TITLE
V2: Device not created in Chirpstack. Error in waziup.wazigate-lora

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#104]
Currently, when I create a LoRaWAN device on the UI, it is not created in Chirpstack.

Here is the log of waziup.wazigate-lora:
```
$ docker logs -f waziup.wazigate-lora
--- Init ChirpStack
The ChirpStack data has not changed.
Err grpc: can not create network-server: rpc error: code = AlreadyExists desc = object already exists
```
It seems that the network-server already exists.
Is it possible to tolerate such error for flexibility?

**Comment by cdupont** [comment]
I tried to delete everything in Chirpstack.
Now I am stuck with the error:
```
--- Init ChirpStack
Network-server "Local Chirpstack Network Server" OK.
The ChirpStack data has not changed.
Err grpc: can not create service-profile: rpc error: code = NotFound desc = object does not exist
```

**Comment by j-forster** [comment]
Was this issue resolved with the changes that we made?

**Comment by cdupont** [comment]
Seems yes. Let me close
