### ISSUE TITLE
V2.1: use LPP for actuation, too

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#105]
Similarly than for uplink, LPP could be used for actuation. The small payload can be an advantage.
This lib could be useful on the Arduino side: https://github.com/Alarevoyure/LPP-DECODE

Digital Output could be used:
https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload

The mapping from JSON to LPP could be a little awkward, though.
```
JSON         LPP
Number -> Digital Output from 0 to 255. Other numbers -> not sent
Boolean -> Digital Output 0 and 1
Null -> Digital Output 0
others -> not supported (not sent)
```

**Comment by j-forster** [comment]
This feature is not going to land on v2 in time.
The v3 will cover different payload formats for upstream and downstream, together with the payload encoding / transport layer abstraction.

**Comment by cdupont** [comment]
Let's move to V2.1? or V3?

**Comment by cdupont** [comment]
Moved

**Comment by j-forster** [comment]
This issue will be covered by https://github.com/Waziup/WaziGate/issues/121.
I will close this now in favor of the new issue.
