### ISSUE TITLE
V2: not clear if update finished

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#106]
I got this after a long time:
![image](https://user-images.githubusercontent.com/484033/99654429-962eba00-2a5a-11eb-869d-c514d07b279e.png)

It's not clear if the update finished?

**Comment by mojtaba-esk** [comment]
Did you check the actual logs of the wazigate-edge container? usually this log window should show some message when update finishes.

**Comment by cdupont** [comment]
Not reproduced, closing
