### ISSUE TITLE
V2: missing sensors and actuators details

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#108]
Some details are missing in sensors and actuator view:
![image](https://user-images.githubusercontent.com/484033/99661425-1a396f80-2a64-11eb-882a-6c1231b5574f.png)

It would be nice to have e.g. last sensor value displayed.

**Comment by j-forster** [comment]
This has been fixed by https://github.com/Waziup/wazigate-dashboard/commit/1c2f0a663056f19af44ba3abf3dcba5f1556d3b2.

**Comment by cdupont** [comment]
Nice, seems to work.
However, why not setting the sensor kind?
![image](https://user-images.githubusercontent.com/484033/99957826-998eb200-2d88-11eb-97c3-7aa704c6dce5.png)

Another remark, why not displaying the value on this page?
![image](https://user-images.githubusercontent.com/484033/99957893-b0350900-2d88-11eb-9ff0-40c02a040c30.png)

**Comment by cdupont** [comment]
The paper could be open by default, so we can see the value immediately when we open the page.

**Comment by cdupont** [comment]
Closing as the main action is done.
We can reopen another issue for the other remarks.
