### ISSUE TITLE
V2.1: use default LoRaWAN keys for WaziDev

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#111]
In order to make it easy to use with WaziDev, we could have default keys for DEVADDR, NWKSKEY and APPSKEY.
This way, the WaziDev would work immediately after flashing.

**Comment by j-forster** [comment]
We can unify NWKSKEY and APPSKEY but, but having default keys defies the LoRaWAN security completly.
However, users are allowed to use the unchanged keys from the Wazidev tutorials and example codes.

Besides that, DevAddr must be unique for all local devices.

**Comment by cdupont** [comment]
`We can unify NWKSKEY and APPSKEY but, but having default keys defies the LoRaWAN security completly.`
Good idea, let me put the same key in the LoRaWAN examples.

The idea would be that the WaziGate would "know" a default profile for WaziDev quick testing. For example, a profile called "WaziDev-default-keys". We can even add a mention "unsafe, make sure to change the keys before using in production".
This would allow the total beginner to understand what are keys, where to get them and where to copy them properly.

Johann waiit before closing :) Issue need to be discussed :)
