### ISSUE TITLE
V2: Values not uploaded anymore

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#113]
After some network interruption, I could not get my WaziDev values on the dashboard anymore.

I get this in waziget-lora:
```
--- Init Device
GET devices?meta=lorawan: 200 OK
DevEUI AA555A002601143F -> Waziup ID 5fbba5f75721cf0006e3ced6
Reactivating Chirpstack device ... OK
There are 1 LoRaWAN devices.
Err EOF
```

**Comment by j-forster** [comment]
Is there some more error log? Did the container restart?

**Comment by cdupont** [comment]
I rebooted everything.
Chirpstack receives the messages correctly:
![image](https://user-images.githubusercontent.com/484033/100125714-5cf0b280-2e7d-11eb-8eb4-0799259578f2.png)

**Comment by j-forster** [comment]
The EOF error was resolved by https://github.com/Waziup/wazigate-lora/commit/a1be1e1b5e9f434597e03603d16d25b4aa72ea42.

**Comment by cdupont** [comment]
I don't see the error anymore. Closing
