### ISSUE TITLE
V2: Missing actuation page

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#114]
When navigating to an actuator, I get:
![image](https://user-images.githubusercontent.com/484033/99979542-7e7f6a80-2da7-11eb-9758-3aec74c32104.png)

**Comment by j-forster** [comment]
The error is now hidden via https://github.com/Waziup/wazigate-dashboard/commit/5c19ad45f89b17c85f7ae3e1fdd4786cb88b1827.

**Comment by cdupont** [comment]
looks good, closing!
