### ISSUE TITLE
V2.1: Help link broken for apps

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#118]
The help link is broken for all apps in the app box:

![image](https://user-images.githubusercontent.com/484033/100145872-47898180-2e99-11eb-964d-a37d06d7997e.png)

**Comment by mojtaba-esk** [comment]
Is there a help link?

**Comment by cdupont** [comment]
If I click on e.g. "waziup.wazigate-lora" (in grey in the above picture), it brings me here:

![image](https://user-images.githubusercontent.com/484033/100209634-683def80-2f0a-11eb-97d9-177aa7c68f53.png)

**Comment by mojtaba-esk** [comment]
The link on each App, in the App manager, is set by the developer in `package.json` file. So one must make sure the link is not a dead one.

**Comment by mojtaba-esk** [comment]
If no link is provided, the App manager generates a link to the docker hub page of the main image where developers can also provide some information.
