### ISSUE TITLE
V2: downlink not working with single_chan_pkt_fwd 

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#120]
This is the trace I get:
```
Waziup ID 5fbba5f75721cf0006e3ced6 -> DevEUI AA555A002601143F
Payload (true) dHJ1ZQ==
Payload enqueued: FCnt 30
Unknown MQTT topic "application/55/device/aa555a002601143f/txack".
```

**Comment by j-forster** [comment]
The `txack` is the message from ChirpStack that the downlink completed.
Reading this topic is just for logging, which has been improved by https://github.com/Waziup/wazigate-lora/commit/b4c5445b192facc831badfad6d0bac5b1a34d307.

**Comment by cdupont** [comment]
Duplicate of #134, closing
