### ISSUE TITLE
Error installing Python sample app

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#123]
I got this when trying to install the Python hello world app:
![image](https://user-images.githubusercontent.com/484033/101023458-16810f00-3573-11eb-8824-aebe510f2e54.png)

**Comment by cdupont** [comment]
Also a typo in this message:
![image](https://user-images.githubusercontent.com/484033/101023845-9dce8280-3573-11eb-8843-6191471c99c8.png)

**Comment by mojtaba-esk** [comment]
Fixed

**Comment by cdupont** [comment]
closing for lack of updates
