### ISSUE TITLE
Error when saving LoRaWAN keys

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#127]
I got this error while trying to save LoRaWAN keys:

![image](https://user-images.githubusercontent.com/484033/101181736-8663c800-364d-11eb-88da-45441560b8a0.png)

**Comment by j-forster** [comment]
This error has been fixed by https://github.com/Waziup/wazigate-edge/commit/a88e540e8c06682a48435b4d291cfd83db6bdd3e.

**Comment by cdupont** [comment]
Fixed! Closing
