### ISSUE TITLE
Warnings will compiling wazigate-dashboard

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#129]
After typing `npm run build`:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main.js (737 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (737 KiB)
      main.js
```

**Comment by j-forster** [comment]
The warning is right - the file size is in fact very high. The files are served from the local webserver and mostly used within the local network, so this has not the same impact on the user experience as files that are served via the internet.

Also, this file covers all material-UI components that are also used by all the apps, thus reducing the app's size to just a few kilobytes.

This warning does not indicate an error.

**Comment by cdupont** [comment]
OK, thanks
