### ISSUE TITLE
Sync, confusing default login

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#130]
The default login displayed (after flashing ISO V2.1.1) is "admin":
![image](https://user-images.githubusercontent.com/484033/101660091-125b6280-3a47-11eb-85a3-a1dafd8af13c.png)

This is confusing for the user: he will think "this is the same login than WaziGate UI, i.e. admin/loragateway".
Furthermore, there is no chance that "admin" is a valid login for WaziCloud.

**Comment by j-forster** [comment]
There are no default username and no default password in the config files:
https://github.com/Waziup/wazigate-edge/blob/v2/clouds.json
https://github.com/Waziup/WaziGate/blob/master/setup/clouds.json
Is this a old artifact from your the build process @mojtaba-esk?

**Comment by mojtaba-esk** [comment]
That user and password is coming from your browser because they are stored in the browser. Any website loads on that domain/ip, the browser fills the user and password fields automatically. User should be aware of that.

**Comment by cdupont** [comment]
I see, thanks.
I've never put "admin" in this field, so that's strange.
I think the "autocomplete" browser feature is based on the `name` of the form field? In our case, I think the `name` in the Sync form is the same than in the login form, which might explain why my browser picked `admin`:
![image](https://user-images.githubusercontent.com/484033/101754095-a541de80-3ad3-11eb-8038-b7b9e80ae71d.png)
Maybe better to change the name as "cloud_username", just to avoid confusion?
