### ISSUE TITLE
MQTT Error EOF after connect

### ISSUE THREAD

**Issue by j-forster** [Waziup/WaziGate#136]
From the wazigate-edge logs on a new v2.1.3 Wazigate:

```
[UP   ] Connecting to MQTT as "j.forster" ...
[UP   ] (500) Communication Error
MQTT communication error:
EOF
```

MQTT seems to break right after the connect. Either the cloud closes the connection unexpectedly, or the error originates in the gateway.

**Comment by j-forster** [comment]
Testing with mosquitto, no connection can be established:
```
> mosquitto_sub -L mqtt://name:password@api2.waziup.io/devices/5eafcd6a4b9f612a70ab6d96/tunnel-down/+ -v -d
< Client mosqsub|10192-DESKTOP-L sending CONNECT
< Client mosqsub|10192-DESKTOP-L sending CONNECT
```
It seems to be a server issue.

**Comment by cdupont** [comment]
let me look

**Comment by cdupont** [comment]
It seems that the problem is with authentication. Without auth, it works.

**Comment by j-forster** [comment]
What can be done to fix this? Are there changes on the permission system that have broken the [wazigate-tunnel](https://github.com/Waziup/wazigate-tunnel)?

**Comment by cdupont** [comment]
OK, it should work now.
A small problem with MQTT logins. I let you close if fixed.

**Comment by cdupont** [comment]
I see connected gateways came back on the Cloud dashboard :)
