### ISSUE TITLE
Apps UI "Update" button flashing

### ISSUE THREAD

**Issue by j-forster** [Waziup/WaziGate#137]
When opening the Apps panel, the "Update" button flashes (to indicate, that it's searching for new updates?).

![waziapp update](https://user-images.githubusercontent.com/25847959/104017080-c15e9b80-51b7-11eb-928c-2c71bdca8cb1.png)

Some users got confused and did not know what the App is doing right now.
Can we improve this by writing "Checking for updates..." on the UI?

**Comment by mojtaba-esk** [comment]
Fixed: A tooltip added to tell the user what is going on
