### ISSUE TITLE
Update of Wazigate Edge Framework from v2.1.9. shows still v2.1.9. after update

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziGate#146]
![image](https://user-images.githubusercontent.com/62630067/109237746-78e45700-77d2-11eb-9171-1d563da1757e.png)
The version number has been kept constant after an update. It should have been increased by at least one.

**Comment by j-forster** [comment]
I pushed new images of wazigate-edge and waigate-lora to the Docker hub but forgot to increase the version number. @mojtaba-esk  already told me about my mistake...
