### ISSUE TITLE
Update of wazigate-lora from v0.18.8  results again in version number v0.18.8

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziGate#147]
It appears wired, that the version number does not count up at least by one, if an update takes place (here it was from v0.18.8 ...and it kept staying at v0.18.8 after the update) ...see figures below:

![image](https://user-images.githubusercontent.com/62630067/109237901-d082c280-77d2-11eb-9abe-c6ba2308fc56.png)

![image](https://user-images.githubusercontent.com/62630067/109238150-4a1ab080-77d3-11eb-916e-2bf5a979e80b.png)

![image](https://user-images.githubusercontent.com/62630067/109239500-e04fd600-77d5-11eb-88a1-26ea52ecb3ac.png)

![image](https://user-images.githubusercontent.com/62630067/109239603-168d5580-77d6-11eb-9772-c258d524b4f7.png)

**Comment by j-forster** [comment]
I pushed new images of wazigate-edge and waigate-lora to the Docker hub but forgot to increase the version number. @mojtaba-esk already told by about my mistake...
