### ISSUE TITLE
Docker fail after running the gateway for several days

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/WaziGate#157]
We deployed a gateway and keep it running for several days. A couple of containers were stopped working since yesterday and once I tried to run them with docker-compose, I got this error:

Running Edge:

```
ERROR: layer does not exist
```
Running Redis:

```
Starting redis ... error

ERROR: for redis  Cannot start service redis: runtime: failed to create new OS thread (have 8 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

**Comment by cdupont** [comment]
closing as not reproduced
