### ISSUE TITLE
Redis doesn't stop restarting

### ISSUE THREAD

**Issue by teegwende** [Waziup/WaziGate#167]
Hello guys,
I am facing  a problem with redis. It doesn't stop restarting. I am using wazigate version 2.20. I need help to handle this. Thanks

**Comment by cdupont** [comment]
Hi Zougmore,
it seems it's an old version... Could you include some logs?

**Comment by teegwende** [comment]
Hello Corentin, unfortunately, I didn't make some snapshots. The irrigation system is deployed on a site a little far from the town. The message was relative a to a bad file format with a recommendation to run redis-check-aof command. If this information isn't enough, I will send later, the logs. Thanks !

**Comment by cdupont** [comment]
I could be that your SD card got corrupted. Is that case the simplest is to flash the new version.
The latest is V2.3.2: https://downloads.waziup.io/
In this version we worked on optimizing SD card with much better performance.
https://github.com/Waziup/WaziGate/blob/master/ChangeLog.md

**Comment by cdupont** [comment]
@24inch @j-forster

**Comment by teegwende** [comment]
Thanks a lot for your answer. I will give a try. But is there a way to save data already collected ?

**Comment by teegwende** [comment]
Hello Corentin, I hope you are ok. Finally, I was able to resolve the problem. I stopped the redis container and deleted a directory named _data. After I restarted the redis container. 
I have faced other difficulties. I will open a new issue to explain that
