### ISSUE TITLE
Check NTP

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#20]
Some versions of Raspbian are missing the time server NTP: https://www.raspberrypi.org/forums/viewtopic.php?t=192020

The gateway at iLab was 7 days late. Pushing the data from Edge to Cloud was failing because the HTTPS certificates could not be validated.

**Comment by mojtaba-esk** [comment]
I have fixed it, could you please double check it?

**Comment by cdupont** [comment]
Tested, working
