### ISSUE TITLE
Number values

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#21]
It seems that the current gateway pushes only strings for the sensor measurements:
```
"value":"202"
```
However, measurement should be uploaded as numbers. This is better for calculations, such as for calibrations or notification conditions.
The old gateway was uploading as numbers:
```
"value": 202
```
It seems that Congduc was performing a test and casting the value:
https://github.com/CongducPham/LowCostLoRaGw/blob/master/gw_full_latest/CloudWAZIUP.py#L419

**Comment by cdupont** [comment]
Temporary solution: I do the conversion on the Cloud side. https://github.com/Waziup/waziup-api/commit/d597b7e3e063ca47d9e36a217324b2f2289a4491
This patch can be removed when the gateway is updated.

**Comment by mojtaba-esk** [comment]
Fixed.
