### ISSUE TITLE
Error message on the UI when Cloud credentials are wrong

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#22]
On the gateway UI, a message should appear if the user Cloud credentials are wrong.

**Comment by cdupont** [comment]
How can this be done? I think the Edge create the resources on the Cloud in an asynchronous way, right? So we cannot use direct HTTP error codes.

**Comment by j-forster** [comment]
This is a good idea and can be done.
But it will not work if the GW is offline or if the network connection is unstable.

**Comment by mojtaba-esk** [comment]
Thanks for raising this.
It is resolved now
