### ISSUE TITLE
Cloud account: accept old logins

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#27]
The current gateway accepts only emails as login for the Cloud connection. It would be nice if it accepts also old logins, that was created before the "email as login" change. Old logins (such as "cdupont") are still working for those who created the account before the change. I think only a warning could work: "Warning: you entered a login that is not an email. Proceed?".

**Comment by mojtaba-esk** [comment]
Well I think it will be messy, we need to ask them to use their email which is easy for the users to remember and use. Moreover, it will simplify the setup procedure.

**Comment by cdupont** [comment]
Totally agree. My comment was more for the 800 users already registered with normal usernames.
At the Cloud, the User data structure looks like this:
```
{
   username: "user@gmail.com",
   email: "user@gmail.com"
   ...
}
```
Under the new policy "email as username", the Cloud dashboard doesn't ask explicitly a username to users, only an email. However, the field `username` still exists internally. The cloud dashboard uses the email to fill both `username` and `email`. For old users, the username is unchanged.

Regarding the `GET /auth/token` endpoint:
```
{
  "username": "user@gmail.com",
  "password": "password"
}
```
The field used for authentication is still `username` (whether it is effectively filed with an email or an old username).

To make the old accounts work from the gateway, I think there could be two solutions:

1. ask for an email. 
2. ask for a username or email.

For 1., the gateway could retrieve the `username` from the API, using the `GET /users?email=user@gmail.com` endpoint to convert the email into a username. This would ensure that we really have the username. This username could then be used safely for authentication.

For 2., a little case analysis is necessary: if it's a username, use it directly. If it's an email, retrieve the username.

It is also possible to modify the `/auth/token` endpoint, adding the possibility to authenticate with an email:
```
{
  "username": "user@gmail.com",
  "email": "user@gmail.com"
  "password": "password",
}
```
In this case, you could provide either `username` OR `email` field, based on your preference. The Cloud will do the job of retrieving the username from the email.

The point is, I don't think we should completely merge `username` and `email` internally, as they serve different purposes. i.e. `username` is used for login, `email` is used to send mail. I think it is important to keep them separated, even is they have the same value (the email) from now on. This will avoid confusing things in the future.

**Comment by mojtaba-esk** [comment]
I think the simplest and the cleanest way is to replace the usernames with emails in the database on cloud. Otherwise we have to add more complexities to the edge on the gateway.

**Comment by cdupont** [comment]
Working, closing
