### ISSUE TITLE
Remote tunnel does not authenticate

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/WaziGate#29]
Remote access to the gateway through MQTT tunnel does not go through due to an issue in authentication. Please have a look at the screenshot:

![image](https://user-images.githubusercontent.com/13765532/68309649-04524a00-00af-11ea-9e1f-c785094f0d95.png)

It seems that double slash appears instead of single one in redirection.

I don't know it's related to Corentin's job or Johann's.

**Comment by cdupont** [comment]
I have the same problem

**Comment by cdupont** [comment]
fixed
