### ISSUE TITLE
"No internet" displayed, even with internet

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#32]
![Screenshot from 2019-11-15 12-18-58](https://user-images.githubusercontent.com/484033/68940018-5c213d00-07a2-11ea-810f-4a9e84790ea2.png)
However the connectivity seems to be working. I can ping google through both eth0 and wlan0.

**Comment by mojtaba-esk** [comment]
are you sure it pushes the data to the cloud?

**Comment by cdupont** [comment]
I retried with a freshly flashed gateway, it also says "no internet". Note that I use also the cable.
I don't think it pushes to the Cloud.

**Comment by mojtaba-esk** [comment]
are you sure you can ping waziup.io on your pi?

**Comment by mojtaba-esk** [comment]
Fixed

**Comment by cdupont** [comment]
Tested

**Comment by cdupont** [comment]
This problem shows on several gateways that has been flashed by our African partners:

![Screenshot from 2020-01-23 16-42-37](https://user-images.githubusercontent.com/484033/72999610-e53a9d00-3dff-11ea-94a4-3ddcebbafa27.png)
