### ISSUE TITLE
change login: wrong pre-fill

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#37]
The field "New Username" is already filled with my current username. I think this should be the "Current Username" field.
![Screenshot from 2019-11-15 13-44-45](https://user-images.githubusercontent.com/484033/68944432-1c605280-07ae-11ea-9a13-2ac9df9c2c7b.png)

**Comment by cdupont** [comment]
After changing login/password, there is no pre-fill:
![Screenshot from 2019-11-15 13-47-18](https://user-images.githubusercontent.com/484033/68944604-7e20bc80-07ae-11ea-813b-cc70f6b3caf1.png)

Anyway, pre-filling the password might be dangerous?

**Comment by mojtaba-esk** [comment]
This is not a bug. It is because your credential is stored in your browser and this happens in all websites.

**Comment by cdupont** [comment]
Tested: OK
