### ISSUE TITLE
Notification menu doesn't open

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#38]
![Peek 2019-11-15 13-57](https://user-images.githubusercontent.com/484033/68945139-f76cdf00-07af-11ea-9551-ecd6b0e9684e.gif)

**Comment by cdupont** [comment]
I think in this version it should be hidden/removed.

**Comment by mojtaba-esk** [comment]
Notification is not a menu, it's just a page which opens in your gif.

**Comment by cdupont** [comment]
Tested: OK (menu hidden)
