### ISSUE TITLE
LoRa data with device ID doesn't work

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#41]
Sending the following string over LoRa: “\!ID/DeviceTEST/TC/16.75”
It should create a device with ID "12345" and a sensor "TC".
However it used the automatic device ID (based on gateway ID) and created a sensor named "ID":
![Screenshot from 2019-11-15 15-33-30](https://user-images.githubusercontent.com/484033/68951020-9c41e900-07bd-11ea-8f81-f0faa319de79.png)

**Comment by mojtaba-esk** [comment]
you should use **UID** not ID.

**Comment by cdupont** [comment]
Thanks that's right, closing.
