### ISSUE TITLE
OLED infos

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#62]
I got this screen:
![20200220_161158](https://user-images.githubusercontent.com/484033/74948507-b282c500-53fc-11ea-84dd-35e97f10149a.jpg)

It would be nice to keep some information displayed all the time. Such as:
- AP: Off
- Eth: not connected
- Wifi: not connected

**Comment by mojtaba-esk** [comment]
due to limited space we have on the OLED, these information shown when available. for example if Ethernet is not connected, it does not show it. and the same for WiFi and AP.
