### ISSUE TITLE
Clients are kicked out when connected to the AP mode for a while

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/WaziGate#70]
Here is the log when it gets disconnected:

> Jan 22 19:13:17 wazigate ntpd[1044]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:13:25 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> Jan 22 19:13:25 wazigate dhcpcd[4029]: wlan0: carrier lost
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Interface wlan0.IPv6 no longer relevant for mDNS.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Leaving mDNS multicast group on interface wlan0.IPv6 with address fe80::b57f:1b1a:df9:3d9c.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Interface wlan0.IPv4 no longer relevant for mDNS.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.200.1.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Withdrawing address record for fe80::b57f:1b1a:df9:3d9c on wlan0.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Withdrawing address record for 192.168.200.1 on wlan0.
> Jan 22 19:13:25 wazigate hostapd[3471]: wlan0: STA 00:00:00:00:00:00 IEEE 802.11: disassociated
> Jan 22 19:13:25 wazigate NetworkManager[345]: <info>  [1579716805.9236] device (wlan0): set-hw-addr: set MAC address to 76:97:F0:BD:78:51 (scanning)
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.200.1.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: New relevant interface wlan0.IPv4 for mDNS.
> Jan 22 19:13:25 wazigate avahi-daemon[336]: Registering new address record for 192.168.200.1 on wlan0.IPv4.
> Jan 22 19:13:25 wazigate kernel: IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> Jan 22 19:13:25 wazigate NetworkManager[345]: <info>  [1579716805.9583] device (wlan0): supplicant interface state: ready -> disabled
> Jan 22 19:13:25 wazigate NetworkManager[345]: <info>  [1579716805.9607] device (wlan0): supplicant interface state: disabled -> inactive
> Jan 22 19:13:26 wazigate kernel: IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
> Jan 22 19:13:26 wazigate avahi-daemon[336]: Withdrawing address record for 192.168.200.1 on wlan0.
> Jan 22 19:13:26 wazigate avahi-daemon[336]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.200.1.
> Jan 22 19:13:26 wazigate wpa_supplicant[337]: wlan0: Reject scan trigger since one is already pending
> Jan 22 19:13:26 wazigate avahi-daemon[336]: Interface wlan0.IPv4 no longer relevant for mDNS.
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: deleting route to 192.168.200.0/24
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: deleting default route via 192.168.200.1
> Jan 22 19:13:26 wazigate dnsmasq[3491]: no servers found in /run/dnsmasq/resolv.conf, will retry
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: new hardware address: 76:97:f0:bd:78:51
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: carrier acquired
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: IAID f0:bd:78:51
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: adding address fe80::66f6:b791:bdb:6a13
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: probing address 192.168.200.1/24
> Jan 22 19:13:26 wazigate avahi-daemon[336]: Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::66f6:b791:bdb:6a13.
> Jan 22 19:13:26 wazigate avahi-daemon[336]: New relevant interface wlan0.IPv6 for mDNS.
> Jan 22 19:13:26 wazigate avahi-daemon[336]: Registering new address record for fe80::66f6:b791:bdb:6a13 on wlan0.*.
> Jan 22 19:13:26 wazigate dhcpcd[4029]: wlan0: soliciting an IPv6 router
> Jan 22 19:13:27 wazigate ntpd[1044]: bind(25) AF_INET6 fe80::66f6:b791:bdb:6a13%3#123 flags 0x11 failed: Cannot assign requested address
> Jan 22 19:13:27 wazigate ntpd[1044]: unable to create socket on wlan0 (6) for fe80::66f6:b791:bdb:6a13%3#123
> Jan 22 19:13:27 wazigate ntpd[1044]: failed to init interface for address fe80::66f6:b791:bdb:6a13%3
> Jan 22 19:13:27 wazigate ntpd[1044]: Deleting interface #4 wlan0, fe80::b57f:1b1a:df9:3d9c%3#123, interface stats: received=0, sent=0, dropped=0, active_time=245 secs
> Jan 22 19:13:27 wazigate ntpd[1044]: Deleting interface #5 wlan0, 192.168.200.1#123, interface stats: received=0, sent=0, dropped=0, active_time=241 secs
> Jan 22 19:13:27 wazigate ntpd[1044]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:13:27 wazigate ntpd[1044]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:13:29 wazigate ntpd[1044]: Listen normally on 7 wlan0 [fe80::66f6:b791:bdb:6a13%3]:123
> Jan 22 19:13:29 wazigate ntpd[1044]: new interface(s) found: waking up resolver
> Jan 22 19:13:29 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: associated
> Jan 22 19:13:32 wazigate dhcpcd[4029]: wlan0: using static address 192.168.200.1/24
> Jan 22 19:13:32 wazigate avahi-daemon[336]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.200.1.
> Jan 22 19:13:32 wazigate avahi-daemon[336]: New relevant interface wlan0.IPv4 for mDNS.
> Jan 22 19:13:32 wazigate dhcpcd[4029]: wlan0: adding route to 192.168.200.0/24
> Jan 22 19:13:32 wazigate dhcpcd[4029]: wlan0: adding default route via 192.168.200.1
> Jan 22 19:13:32 wazigate avahi-daemon[336]: Registering new address record for 192.168.200.1 on wlan0.IPv4.
> Jan 22 19:13:32 wazigate dnsmasq[3491]: reading /run/dnsmasq/resolv.conf
> Jan 22 19:13:32 wazigate dnsmasq[3491]: ignoring nameserver 192.168.200.1 - local interface
> Jan 22 19:13:32 wazigate dnsmasq[3491]: using nameserver 8.8.8.8#53
> Jan 22 19:13:32 wazigate dnsmasq[3491]: using nameserver fd51:42f8:caae:d92e::1#53
> Jan 22 19:13:33 wazigate ntpd[1044]: Listen normally on 8 wlan0 192.168.200.1:123
> Jan 22 19:13:33 wazigate ntpd[1044]: new interface(s) found: waking up resolver
> Jan 22 19:13:33 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> Jan 22 19:13:33 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: associated
> Jan 22 19:13:37 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> Jan 22 19:13:37 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: associated
> Jan 22 19:13:40 wazigate dhcpcd[4029]: wlan0: no IPv6 Routers available
> Jan 22 19:13:41 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> Jan 22 19:13:41 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: associated
> Jan 22 19:13:45 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> Jan 22 19:13:45 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: associated
> Jan 22 19:13:49 wazigate hostapd[3471]: wlan0: STA a0:88:69:e8:00:71 IEEE 802.11: disassociated
> 
> Jan 22 19:14:14 wazigate ntpd[1044]: error resolving pool 1.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:24 wazigate ntpd[1044]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> 
> 
> 
> 
> Jan 22 19:14:34 wazigate ntpd[1044]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:40 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: associated
> Jan 22 19:14:44 wazigate ntpd[1044]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:44 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:50 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:52 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:52 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: associated
> Jan 22 19:14:56 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:14 wazigate ntpd[1044]: error resolving pool 1.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:24 wazigate ntpd[1044]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> 
> 
> 
> 
> Jan 22 19:14:34 wazigate ntpd[1044]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:40 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: associated
> Jan 22 19:14:44 wazigate ntpd[1044]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)
> Jan 22 19:14:44 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:50 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:52 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated
> Jan 22 19:14:52 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: associated
> Jan 22 19:14:56 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociatedJan 22 19:15:13 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: associated
> Jan 22 19:15:17 wazigate hostapd[3471]: wlan0: STA 20:0d:b0:12:b2:38 IEEE 802.11: disassociated

**Comment by mojtaba-esk** [comment]
Resolved this way:



To fix this you need edit NetworkManager config file:

`sudo nano /etc/NetworkManager/NetworkManager.conf`

 and add below 2 lines:

```
[device]
wifi.scan-rand-mac-address=no
```

**Comment by cdupont** [comment]
Fixed here: https://github.com/Waziup/WaziGate/commit/9215b6ef704830b6caee1aaf755cc29bea925773
Released in V1.1.3
