### ISSUE TITLE
V2: LoRaWAN: Disable frame counter by default for WaziDev profile

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#82]
As WaziDev is a development platform, I think frame counter should be disabled by default.
Otherwise, this will give a lot of headaches to users, as the device is re-flashed/restarted all the time.
They always have the possibility of re-enabling it if they want to go more serious.

**Comment by j-forster** [comment]
This issue introduces some security holes to the Wazigate, but we decided to add the "frame-counter validation skip" for the Wazigate / Wazidev development platform.

https://github.com/Waziup/wazigate-lora/commit/63d810c9cd3781ce7ae02a6dc9868b86a72d81de

**Comment by cdupont** [comment]
Thanks, so the "frame-counter validation skip" is true by default right? Although it can be set to false by the dev?
