### ISSUE TITLE
V2: update issues

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#84]
I created this issue to centralize some comments about the updates in V2.

1. Apps panel

![image](https://user-images.githubusercontent.com/484033/96855090-8d979380-145c-11eb-9fa2-490fb63d0ba2.png)

- "status:running" is missing a space (this info could be an icon)
- The current version is not clearly visible

2. Settings panel

![image](https://user-images.githubusercontent.com/484033/96855377-ebc47680-145c-11eb-9067-3870c188232a.png)

- it's not clear why some buttons are greyed out. Maybe mention that this app is "System" and cannot be deleted/stopped.
- It's not clear if my version is the last, or if there is new versions available.

3. Update

![image](https://user-images.githubusercontent.com/484033/96855873-9ccb1100-145d-11eb-8766-fba9aa2259c7.png)
![image](https://user-images.githubusercontent.com/484033/96856369-1e22a380-145e-11eb-88ef-1b45609fc73d.png)

- There is no "close" button.
- Maybe the button "check for updates" should be inside the box, close to the current version. Currently it's on the bottom right, which suggests that it's an exit button.
- After clicking on "Check for updates", the button becomes "Update now", but it's hard to notice. The new version number is not visible.
- After clicking on "Update now", the old button "Check for updates" comes back with a timer on it, suggesting the update is going on. However, it's not clear that things are installing, apart from the timer.
- During an update, I wonder if it's possible to put a progress bar instead, and hide a bit the logs box (as it's quite technical infos).
- The logs box is not well dimensioned. 
- I can exit the panel during an update, which seems OK. The corresponding "Update" button on the app is blinking grey/back.
However, it's not clear when the update is finished, and what I should do next.

**Comment by mojtaba-esk** [comment]
The absence of close button and the location of buttons are part of the UI design proposed by Johann and I think it is nice.
The rest of issues are resolved in Edge version 2.1.5, please update.

**Comment by cdupont** [comment]
- [x] It's not clear if my version is the last, or if there is new versions available. **OK**
- [x] The current version is not clearly visible: **better now**
- [x] "status:running" is missing a space **OK**
- [x] The logs box is not well dimensioned. **OK**
- [x] After clicking on "Check for updates", the button becomes "Update now", but it's hard to notice. **OK**
- [x] After clicking on "Update now", the old button "Check for updates" comes back with a timer on it, suggesting the update is going on. However, it's not clear that things are installing, apart from the timer.
- [ ] it's not clear why some buttons are greyed out. Maybe mention that this app is "System" and cannot be deleted/stopped.
- [ ] Maybe the button "check for updates" should be inside the box, close to the current version. Currently it's on the bottom right, which suggests that it's an exit button.
- [ ] During an update, I wonder if it's possible to put a progress bar instead, and hide a bit the logs box (as it's quite technical infos).

**Comment by mojtaba-esk** [comment]
>>  it's not clear why some buttons are greyed out. Maybe mention that this app is "System" and cannot be deleted/stopped.
It is just disabled and curios users should not mess with them up ;)

>> Maybe the button "check for updates" should be inside the box, close to the current version. Currently it's on the bottom right, which suggests that it's an exit button.
Their current place is coherent with the rest of the UI design. Otherwise it confuses the user.

>> After clicking on "Update now", the old button "Check for updates" comes back with a timer on it, suggesting the update is going on. However, it's not clear that things are installing, apart from the timer.
Fixed, update please.

>> During an update, I wonder if it's possible to put a progress bar instead, and hide a bit the logs box (as it's quite technical infos).
Currently not possible.

**Comment by cdupont** [comment]
Thanks for the comments and fixes. I retested, it works well! Closing.
