### ISSUE TITLE
V2: missing favicon

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#85]
The web app is missing a favicon on the tab:
![image](https://user-images.githubusercontent.com/484033/96861286-2aa9fa80-1464-11eb-9f77-9bebbd8af892.png)

**Comment by cdupont** [comment]
Tested today, still missing

**Comment by cdupont** [comment]
favicon is a 404 error:
![image](https://user-images.githubusercontent.com/484033/99661277-e6f6e080-2a63-11eb-89af-ce40ccf9bda2.png)

**Comment by j-forster** [comment]
This has been fixed by https://github.com/Waziup/wazigate-edge/commit/2ee69b8e5596b0ec3f0b4db203fdb1ce5f502b33.

**Comment by cdupont** [comment]
Works!
