### ISSUE TITLE
V2: Wifi enhancements

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#88]
I create this issue to collect some problems about Wifi connection (mainly small UI improvements).

![image](https://user-images.githubusercontent.com/484033/97160268-5f77c380-177c-11eb-9c75-c2f5ac638730.png)

Some small improvements:
- the Wifi icons on the left are more of less grey according to wifi signal. It's not very clear, maybe better to use the convention of on/two/three bars to show signal strength.
- the bottom "loading" bar appears occasionally. It's not very clear for the user what it is. It's not sure this bar is necessary?
- Maybe add a mention at the top of the list: "Select a network:" to make clear for the user what he has to do.
- Maybe change slightly the mention at the top to "Mode: WiFi Client"/"Mode: Access Point" (like in the "Maintenance" page). This make clearer that it's either one or the other.

![image](https://user-images.githubusercontent.com/484033/97159847-be890880-177b-11eb-8d02-e13c639d5653.png)

Maybe clearer would be to write "Connecting..." rather than "Connected ()".

**Comment by mojtaba-esk** [comment]
Please update the system and test

**Comment by cdupont** [comment]
Hi Moji, which suggestions did you implement?

**Comment by cdupont** [comment]
[ ] the Wifi icons on the left are more of less grey according to wifi signal. It's not very clear, maybe better to use the convention of on/two/three bars to show signal strength. **not done, however the icons seems to have more contrast?**
[x] the bottom "loading" bar appears occasionally. It's not very clear for the user what it is. It's not sure this bar is necessary? **OK, however there is a small typo in the message**
[x] Maybe add a mention at the top of the list: "Select a network:" to make clear for the user what he has to do. **OK**
[x] Maybe change slightly the mention at the top to "Mode: WiFi Client"/"Mode: Access Point" (like in the "Maintenance" page). This make clearer that it's either one or the other **OK**
[x] Maybe clearer would be to write "Connecting..." rather than "Connected ()". **OK**

This looks good, so let me close this one (we can reopen another one for further changes).
