### ISSUE TITLE
UI displays containers from other apps

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#9]
![Screenshot from 2019-07-11 10-38-55](https://user-images.githubusercontent.com/484033/61031811-e9095380-a3c8-11e9-9f46-be9430848e31.png)

As you can see in the screenshot, the UI displays the status of containers that does not belong to Waziup. I wonder if this is correct? Maybe the user has other applications running.
There will be WaziApps running in the future, but I thing we will prepare a specific UI/section for this purpose.

**Comment by mojtaba-esk** [comment]
Yes this is correct, it lists all the containers created on the device. For waziapps we need to come to a decision then we will separate it if needed.
