### ISSUE TITLE
V2: inconsistant gateway ID

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#92]
- In Chirpstack UI I have AA55A0000000000
- In waziup-gateway/apps/waziup/wazigate-lora/conf/single_chan_pkt_fwd/global_conf.json I have AA555A0000000000

![image](https://user-images.githubusercontent.com/484033/97464912-ca262c00-1941-11eb-89e8-9d67965144f4.png)

**Comment by cdupont** [comment]
Detected again today, ISO: 2.0.1, Edge: 2.1.4, LoRa: 0.17.1

I thought it was fixed (where)?

**Comment by cdupont** [comment]
related issue: https://github.com/Waziup/WaziGate/issues/81

There is a mismatch in the conf, between here: https://github.com/Waziup/wazigate-lora/blob/v2/app/conf/wazigate-lora/chirpstack.json#L24 and here: https://github.com/Waziup/wazigate-lora/blob/v2/app/conf/single_chan_pkt_fwd/global_conf.json#L12

**Comment by mojtaba-esk** [comment]
The latest version of LoRa is no 0.17.1, you must update it to 0.18.1

![image](https://user-images.githubusercontent.com/13765532/97466070-fb532c00-1942-11eb-8076-dda47f596efc.png)

**Comment by cdupont** [comment]
It seems fixed, closing
