### ISSUE TITLE
V2: Update button does not always become orange

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#93]
In the following image, there are updates available, but the button is not orange.

![image](https://user-images.githubusercontent.com/484033/97466585-90562500-1943-11eb-8ecd-ec4ff820ab98.png)

**Comment by mojtaba-esk** [comment]
Fixed

**Comment by cdupont** [comment]
Working well, closing.
The "update" button is blinking, which attracts attention. Maybe a good idea to put an HTML "hint" on over: "Checking for updated... standby" so the user knows what's going on. Or better, change the label of the button to "Checking for updates" and a timer animation, like in the form. 
By the way, the checking is quite long. Why?
