### ISSUE TITLE
V2: device not created on Chirpstack

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#94]
I created a LoRaWAN device on the UI:
![image](https://user-images.githubusercontent.com/484033/97469822-1cb61700-1947-11eb-9903-670587e0c0f1.png)

However, it is not created on Chirpstack:
![image](https://user-images.githubusercontent.com/484033/97469892-3192aa80-1947-11eb-8397-e9806fb9bfbe.png)

**Comment by cdupont** [comment]
Tested with ISO: 2.0.1, Edge: 2.1.4, LoRa: 0.18.1

**Comment by j-forster** [comment]
Should be removed by https://github.com/Waziup/wazigate-lora/commit/1101c36b2d9ae4a9317f6056e7fde026915ec940
