### ISSUE TITLE
V2: "HTTP Error 401 Unauthorized" on update

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#98]
I got this today:
![image](https://user-images.githubusercontent.com/484033/97858118-f9041f80-1cfe-11eb-9282-6ddc56a2a951.png)

Where can it come from? The message is "undefined".

**Comment by mojtaba-esk** [comment]
Maybe you have been logged off right before clicking on the button. Can you please try to re-do it and provide a procedure on how to reproduce the error?

**Comment by cdupont** [comment]
Another such error today, using remote:
![image](https://user-images.githubusercontent.com/484033/99658221-79e14c00-2a5f-11eb-947c-2deac10fa156.png)

Just to understand better, this 401 error is coming from an expired token? Or something else?

**Comment by cdupont** [comment]
I'm not reproducing it. Closing
